# Generated by Django 6.0.4 on 2026-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='descripcion',
            new_name='preparacion',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('Dulce', 'Dulce'), ('Salada', 'Salada')], default='Salada', max_length=10),
            preserve_default=False,
        ),
    ]
