# Generated by Django 6.0.4 on 2026-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
