# Generated by Django 6.0.6 on 2026-07-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_receta_categoria_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('editor', 'Editor'), ('lector', 'Lector')], default='lector', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('Dulce', 'Dulce'), ('Salada', 'Salada')], max_length=20),
        ),
    ]
